import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="z-[1] rounded-ee-[6px] backdrop-blur-[4px] bg-white/10 inline-block absolute left-0 top-0">
          <Link className="p-3 text-4xl inline-block" href="/">
            3D
          </Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
